INHERIT: active-handout.yml

site_name: Técnicas de Programação

extra:
  custom_variables:
    repo_aps: https://github.com/Insper/tecprog-aps
    repo_aps_git: git@github.com:Insper/tecprog-aps.git

nav:
  - 'Home': index.md
  - sobre.md
  - Módulos:
    - "00 - Algoritmos":
      - modulos/00-Algoritmos/index.md
      - modulos/00-Algoritmos/entregas.md
      - "Java":
        - modulos/00-Algoritmos/java/instalacao.md
        - modulos/00-Algoritmos/java/primeiro-contato.md
        - modulos/00-Algoritmos/java/entrada-saida.md
        - modulos/00-Algoritmos/java/strings.md
        - modulos/00-Algoritmos/java/arrays.md
        - modulos/00-Algoritmos/java/interfaces.md
    - "01 - ADT":
      - modulos/01-ADT/index.md
      - "ADTs":
        - modulos/01-ADT/array.md
        - modulos/01-ADT/list.md
        - modulos/01-ADT/map.md
      - "Aulas":
        - modulos/01-ADT/arrays-e-listas.md
        - modulos/01-ADT/listas-e-dicionarios.md
        - modulos/01-ADT/implementacoes-adt.md
      - modulos/01-ADT/aps.md
    - "02 - Busca em vetor":
      - modulos/02-Busca-Vetor/index.md
    - "03 - Ordenação":
      - modulos/03-Ordenacao/index.md
    - "04 - Sistemas Lineares":
      - modulos/04-Sistemas-Lineares/index.md
    - "05 - Busca em Texto":
      - modulos/05-Busca-Texto/index.md
    - "06 - Caminhos":
      - modulos/06-Caminhos/index.md
    - "07 - Mochila":
      - modulos/07-Mochila/index.md
