INHERIT: active-handout.yml

site_name: Técnicas de Programação

nav:
  - 'Home': index.md
  - sobre.md
  - Módulos:
    - "01 - ADT":
      - modulos/01-ADT/index.md
      - "ADTs":
        - modulos/01-ADT/array.md
        - modulos/01-ADT/list.md
        - modulos/01-ADT/map.md
      - "Aulas":
        - modulos/01-ADT/arrays-e-listas.md
        - modulos/01-ADT/listas-e-dicionarios.md
        - modulos/01-ADT/implementacoes-adt.md
      - modulos/01-ADT/aps.md
    - "02 - Busca em vetor":
      - modulos/02-Busca-Vetor/index.md
    - "03 - Ordenação":
      - modulos/03-Ordenacao/index.md
    - "04 - Sistemas Lineares":
      - modulos/04-Sistemas-Lineares/index.md
    - "05 - Busca em Texto":
      - modulos/05-Busca-Texto/index.md
    - "06 - Caminhos":
      - modulos/06-Caminhos/index.md
    - "07 - Mochila":
      - modulos/07-Mochila/index.md
