INHERIT: active-handout.yml

site_name: Técnicas de Programação

extra:
  custom_variables:
    PL_url_course: https://us.prairielearn.com/pl/course_instance/146836

extra_javascript:
  - js/tabs.js

extra_css:
  - css/components.css


nav:
  - 'Home': index.md
  - sobre.md
  - Módulos:
    - "00 - Algoritmos":
      - modulos/00-Algoritmos/index.md
      - modulos/00-Algoritmos/pseudo-codigo-e-java.md
      - modulos/00-Algoritmos/algoritmos-com-arrays-e-strings.md
      - modulos/00-Algoritmos/algoritmos-basicos-strings.md
      - "Java":
        - modulos/00-Algoritmos/java/index.md
        - modulos/00-Algoritmos/java/primeiro-contato.md
        - modulos/00-Algoritmos/java/strings.md
        - modulos/00-Algoritmos/java/arrays.md
        - modulos/00-Algoritmos/java/interfaces.md
    - "01 - Busca em vetor":
      - modulos/01-Busca-Array/index.md
      - "Aulas":
        - "Aula 01":
            - "Buscas básicas": modulos/01-Busca-Array/busca-frente-tras.md
            - "Busca binária I": modulos/01-Busca-Array/busca-binaria-exemplo.md
        - "Aula 02 - Comparando desempenho de algoritmos": modulos/01-Busca-Array/desempenho.md
    - "02 - Estruturas de Dados":
      - modulos/02-Estruturas-de-Dados/index.md
      - "Aulas":
        - "Aulas 01 e 02 - O tipo Lista": modulos/02-Estruturas-de-Dados/arrays-e-listas.md
        - "Aula 03 - Dicionários": modulos/02-Estruturas-de-Dados/listas-e-dicionarios.md
    - "03 - Ordenação":
      - modulos/03-Ordenacao/index.md
      - "Aulas":
        - "01 - Primeiros algoritmos": modulos/03-Ordenacao/ordenacao-simples.md
        - modulos/03-Ordenacao/quick-sort.md
        - modulos/03-Ordenacao/merge-sort.md
    # - "04 - Caminhos":
    #   - modulos/04-Caminhos/index.md
    #   - "Aulas":
    #     - modulos/04-Caminhos/seguir-paredes.md
    #     - modulos/04-Caminhos/dfs.md
    #     - modulos/04-Caminhos/bfs.md
    # - "06 - Mochila":
    #   - modulos/07-Mochila/index.md
    #   - "Aulas":
    #       - modulos/07-Mochila/inicio.md
    - "10 - Extra": modulos/10-Extra/index.md

